### ISSUE TITLE
Bug: compiler fails to process the function with standardlib (using classpath:/)

### ISSUE THREAD

**Issue by trinnguyen** [trinnguyen/bahndsl#12]
```ruby
def request_route(string src_signal_id, string dst_signal_id, string train_id): string
    return get_shortest_route({"r1"})
end
```

**Comment by eyip002** [comment]
When generating `scchart get_shortest_route`, variables declared in an outer scope are not resolved:
- _route_ids:  `immediate do  _result = null [ 0 ] go to S_get_shortest_route_1_0_2`
- _route_id: `immediate do  _length = config_get_scalar_float_value ( "route" , null , "length" ) go to S_get_shortest_route_1_0_3_0_2`
- _min_len: `immediate if _length < null  go to S_get_shortest_route_1_0_3_0_2_0`

**Comment by eyip002** [comment]
Caused by #10

**Comment by eyip002** [comment]
The standardlib has to be validated in order to resolve variable scopes. Otherwise, variable references are not linked to their declarations. This can be done just before BahnModel is validated in `generator/StandaloneApp.java` in `runGenerator()`.

**Comment by eyip002** [comment]
Compilation does not work in Eclipse.
Same waiting problem with VSCode extension.

**Comment by eyip002** [comment]
When setting up the standardlib URI in `BahnImportURIGlobalScopeProvider`, the Xtext resource set load options also have to be set:

`resourceSet.addLoadOption(XtextResource.OPTION_RESOLVE_ALL, Boolean.TRUE);`

**Comment by eyip002** [comment]
Compilation to C and shared library in Eclipse not working.

**Comment by eyip002** [comment]
In Eclipse, the context menu command for compilation creates an instance of `StandaloneApp` which tries to validate the standardlib and model file before the `XtextResourceSet` `setClasspathUriResolver` has been set to our own `CustomClassPathUriResolver`. This causes an exception because standardlib cannot be found in the resourceSets and cannot be loaded with the default classloader.

The fix is to `setClasspathUriResolver` when calling `loadResource` in `StandaloneApp`.

When editing in Eclipse, `BahnScopeProvider` is automatically called, which invokes `BahnImportURIGlobalScopeProvider.getImportedUris()` to set the custom URI resolver.

**Comment by trinnguyen** [comment]
@eyip002 Thanks for solving this!!!
